version: 2
project_name: testplay

builds:
  - id: testplay
    main: ./cmd/testplay
    binary: testplay
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version=v{{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: testplay-storage-helper
    main: ./cmd/testplay-storage-helper
    binary: testplay-storage-helper
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

archives:
  - id: testplay
    ids:
      - testplay
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: testplay-storage-helper
    ids:
      - testplay-storage-helper
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "testplay-storage-helper_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"

release:
  github:
    owner: Kubonsang
    name: testplay-runner
  prerelease: auto
  draft: true
